### ISSUE TITLE
What is timeline for release 2.0.1 or 2.1 ?

### ISSUE THREAD

**Issue by mloskot** [microsoft/windows-container-tools#157]
The most recent release is the ["broken version number" 2.0.0.LM_BUILDMINORVERSION](https://github.com/microsoft/windows-container-tools/issues/145) from June, 2023. Since there have been numerous fixes, some important ones, would it be possible to issue new release of 2.x version line?

p.s. I've realised after the fact, this question may belong to Discussions rather than to Issues

**Comment by iankingori** [comment]
Hey @mloskot, we have 1 performance bug in review then we should get a patch release out early next week: 2.0.1.

**Comment by mloskot** [comment]
Thank you
