### ISSUE TITLE
Tool List - coming soon

### ISSUE THREAD

**Issue by kiquenet** [microsoft/windows-container-tools#167]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when "others coming soon" for Tool List

    Several years ago about it
    
**Describe the solution you'd like**
others tools coming soon in 6 months

**Describe alternatives you've considered**
Never. We want others coming soon

**Additional context**
New tools for docker (windows-container) SOON

**Comment by lucillex** [comment]
Hello, @kiquenet. Thank you for your interest in Windows Containers Tools.

Our team is current adding support for Window Containers to the following key OSS tools: [buildkit](https://github.com/moby/buildkit/issues/616), [nerdctl](https://github.com/containerd/nerdctl), and [minikube](https://github.com/vrapolinario/MinikubeWindowsContainers). In addition, we are working towards open sourcing a [Bootstrapper and Certificate Tool](https://github.com/microsoft/windows-container-tools/issues/98) for 2024.

We'd be interested to learn what additional tools you are seeking along with what use cases you have that are currently not being addressed.
