### ISSUE TITLE
[BUG] After logs are retrieved by LogMonitor.exe it crashes without any error message

### ISSUE THREAD

**Issue by israelvaldez** [microsoft/windows-container-tools#187]
**Describe the bug**
After our application publishes logs into IIS, event log and other log files the LogMonitor.exe crashes without any log message.
Using the same application with the LogMonitor.exe version 2.0.2, we don't get any crashes.

**To Reproduce**
1. Create a pod with LogMonitor.exe as its entrypoint
2. Use the below configuration file for it
```
{
    "LogConfig":  {
                      "sources":  [
                                      {
                                          "eventFormatMultiLine":  false,
                                          "channels":  [
                                                           {
                                                               "level":  "error",
                                                               "name":  "system"
                                                           },
                                                           {
                                                               "level":  "Error",
                                                               "name":  "application"
                                                           },
                                                           {
                                                               "level":  "Verbose",
                                                               "name":  "Epicor App Server"
                                                           }
                                                       ],
                                          "type":  "EventLog",
                                          "startAtOldestRecord":  true
                                      },
                                      {
                                          "filter":  "*.log",
                                          "includeFileNames":  true,
                                          "directory":  "c:\\inetpub\\logs",
                                          "includeSubdirectories":  true,
                                          "type":  "File"
                                      }
                                  ]
                  }
}
```
4. Write some log messages into different locations, like IIS or Event Viewer Logs
5. The Pod crashes with the following error:
    Last State:     Terminated
      Reason:       Error
      Exit Code:    -1073741819
      Started:      Fri, 06 Sep 2024 15:47:20 -0600
      Finished:     Fri, 06 Sep 2024 15:50:20 -0600

**Expected behavior**
The pod should not be terminated.

**Screenshots**
None

**Configuration**
-Tool: Log Monitor
-Version: 2.1.0

**Additional context**
I can provide the docker file separately through an email to you.
I can provide memory dumps of the failure, they were collected using the following procdump command:
procdump -ma -accepteula -n 200 -e -w logmonitor.exe \\vmJumpHost01\Temp\

**Comment by lucillex** [comment]
Thank you for bringing this to our attention, @israelvaldez. Could you please send the docker file and memory dumps to this email: WindowsContainerGitHubIssues@service.microsoft.com. The team would appreciate them as they try to repro the issue.

**Comment by israelvaldez** [comment]
Memory dump and docker file sent to that address.

**Comment by bobsira** [comment]
@israelvaldez can you please confirm the version of Log Monitor you are using? Analyzing the LogMonitor.DMP file you shared shows the version as 2.0.0.0

**Comment by israelvaldez** [comment]
I copied the exe from the container image and it was 2.1.0.

**Comment by bobsira** [comment]
Hey @israelvaldez could you please confirm if this issue still exists in Log Monitor Version 2.1.1. We reverted the change that was causing the failures!

**Comment by israelvaldez** [comment]
We're looking into deploying 2.1.1 into a test cluster to review if this problem is resolved in there. We'll report back once we get this deployed and it is running with what we find.

**Comment by israelvaldez** [comment]
We tried using version 2.1.1 and we didn't get any constant crashes, as we used to do.

**Comment by bobsira** [comment]
Thanks for looking into this!
