### ISSUE TITLE
LogMonitor documentation

### ISSUE THREAD

**Issue by zhammer** [microsoft/windows-container-tools#19]
hey microsoft team! i'm interested in trying Log Monitor for a windows container project. is there any additional documentation on the tool outside of the [windows docker container logs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting#docker-container-logs) troubleshoot page or the example [LogMonitorConfig.json](https://github.com/microsoft/windows-container-tools/blob/master/LogMonitor/src/LogMonitor/sample-config-files/IIS/LogMonitorConfig.json)?

a LogMonitorConfig schema would be particularly helpful. it'd also be helpful to see what Log Monitor output looks like. i'm not entirely sure how messages from different inputs could be differentiated in log monitors stdout.

**Comment by zhammer** [comment]
and one more question: is Log Monitor used in production within microsoft?

**Comment by zhammer** [comment]
ah just found the wiki page - https://github.com/microsoft/windows-container-tools/wiki/Authoring-a-Config-File

**Comment by profnandaa** [comment]
Now we have comprehensive docs in - `/docs` https://github.com/microsoft/windows-container-tools/blob/main/LogMonitor/docs/README.md
