### ISSUE TITLE
No way to identify the source of messages

### ISSUE THREAD

**Issue by mpfiester** [microsoft/windows-container-tools#23]
There's no way to tell from the output what the source of a message is.  For example, if I'm capturing messages from the event viewer logs:

        "type": "EventLog",
        "startAtOldestRecord": true,
        "eventFormatMultiLine": false,
        "channels": [
          {
            "name": "system",
            "level": "Information"
          },
          {
            "name": "application",
            "level": "Error"
          }

The output messages don't identify if the message is from the application or system log.  Or, if I'm capturing from log files:

      {
        "type": "File",
        "directory": "c:\\inetpub\\logs",
        "filter": "*.log",
        "includeSubdirectories": true
      },

The messages don't identify which log the message came from.  It would be very helpful if some additional information was added to the message indicating the source.  In my case, I am capturing information from a set of windows services which each have their own log file.  The log file messages can all look very similar and it's impossible to identify where they're coming from.  The log file name would help.

**Comment by CharityKathure** [comment]
You can now opt to display log file names in the messages by setting the 'includeFileNames' field in [LogMonitorConfig.json](https://github.com/microsoft/windows-container-tools/blob/main/LogMonitor/src/LogMonitor/sample-config-files/IIS/LogMonitorConfig.json) as true.

![image](https://user-images.githubusercontent.com/28774968/178951038-e9c7e631-8fdc-4642-ab9b-bf9e058f8683.png)
