### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/windows-container-tools#25]
I used this config file https://github.com/microsoft/windows-container-tools/blob/master/LogMonitor/src/LogMonitor/sample-config-files/IIS/LogMonitorConfig.json and my dockerfile looks as below:

```
ARG REGISTRY_NAME=acr.azurecr.io
FROM ${REGISTRY_NAME}/os:baseline

COPY ["publish", "/www/os"]

ADD https://build.blob.core.windows.net/logmonitor/LogMonitorConfig.json /LogMonitor/LogMonitorConfig.json
ADD https://build.blob.core.windows.net/logmonitor/LogMonitor.exe /LogMonitor/LogMonitor.exe

WORKDIR /LogMonitor
SHELL ["C:\\LogMonitor\\LogMonitor.exe", "powershell.exe"]

EXPOSE 85

# Start IIS Remote Management and monitor IIS
ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
```

Still I am just seeing **The selected container has not logged any messages yet.** as part of pod logs.. Am I missing any additional setup or config? 

Please help !
@algamaes

**Comment by ricardona** [comment]
Look at an example https://blogs.iis.net/jeonghwan/how-to-use-iis-insider-docker-tag

**Comment by nreddipalle** [comment]
Thank you. That worked. Closing the issue.

**Comment by lucillex** [comment]
Hello @nreddipalle ! Our team would love to hear feedback on how you are using Log Monitor. We've started a thread [here](https://github.com/microsoft/windows-container-tools/issues/84) and invite you to provide your insights.
