### ISSUE TITLE
[LOGMONITOR] INFO: Entrypoint processs exit code: 0

### ISSUE THREAD

**Issue by Kevin-Li-Webjet** [microsoft/windows-container-tools#29]
Whenever I see below log, the pod in Kubernetes will crash in seconds and will restart, it happened intermittently (like 40% chance) after pod started around 3 mins.  And keep going until things go to stable

Log:  =====================================
...
Stopping service 'w3svc'

ERROR: Failed to stop or query status of service 'w3svc' error [800705b4]
[2020-08-20T14:10:32.000Z][LOGMONITOR] INFO: Entrypoint processs exit code: 0

LogMonitorConfig.json:  =====================================
{
    "LogConfig": {
      "sources": [
        {
          "type": "EventLog",
          "startAtOldestRecord": true,
          "eventFormatMultiLine": false,
          "channels": [
            {
              "name": "application",
              "level": "Information"
            }
          ]
        },
        {
          "type": "File",
          "directory": "$directory",
          "filter": "*.log",
          "includeSubdirectories": true
        },
        {
          "type": "ETW",
          "providers": [
            {
              "providerName": "IIS: WWW Server",
              "ProviderGuid": ""$ProviderGuid",
              "level": "Information"
            },
            {
              "providerName": "Microsoft-Windows-IIS-Logging",
              "ProviderGuid": "$ProviderGuid",
              "level": "Information",
              "keywords": "0xFF"
            }
          ]
        }
      ]
    }
  }

Dockerfile: =====================================
...
# Log monitor
RUN [System.Diagnostics.EventLog]::CreateEventSource('TEST.TEST.TEST', 'Application')
RUN $version=$env:LOG_MONITOR_VERSION ; mkdir C:\LogMonitor\ ;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Tls12' ; curl https://github.com/microsoft/windows-container-tools/releases/download/v${version}/LogMonitor.exe -o C:\LogMonitor\LogMonitor.exe
COPY /pipeline/LogMonitorConfig.json /LogMonitor/LogMonitorConfig.json 

...
SHELL ["C:\\LogMonitor\\LogMonitor.exe"]
ENTRYPOINT cmd /c "powershell C:\\startup\\entrypoint.ps1 & C:\\ServiceMonitor.exe w3svc"

**Comment by richshadman** [comment]
I know this is an older issue, however I ran into it and also originally thought it was LogMonitor. Ultimately I discovered it was actually IIS.ServiceMonitor. See here -> https://github.com/microsoft/IIS.ServiceMonitor/issues/49

**Comment by profnandaa** [comment]
As pointed out, this seems to have been on the IIS.ServiceMonitor side and was fixed. Kindly re-open if a related issue arises or if I got it wrong.
