### ISSUE TITLE
[LOGMONITOR] WARNING: Failed to render event log event. The event will not be processed. Error: 15029.

### ISSUE THREAD

**Issue by HaroldZhang91** [microsoft/windows-container-tools#40]
Hi team, I got some error messages from LogMonitor inside docker container:
[LOGMONITOR] WARNING: Failed to render event log event. The event will not be processed. Error: 15029.
[LOGMONITOR] ERROR: Failed to query next event. Error: 1818.
Could you please give us some signs help us resolve this issues?

**Comment by lucillex** [comment]
Hello @HaroldZhang91! Our team would love to hear feedback on you are using Log Monitor. We've started a thread [here](https://github.com/microsoft/windows-container-tools/issues/84) and invite you to provide your insights.
