### ISSUE TITLE
End of Life?

### ISSUE THREAD

**Issue by bulebuk** [microsoft/windows-container-tools#41]
Is this project actively maintained? Microsoft container documentation points to this project as a recommended approach, but the project doesn't appear to be maintained.

**Comment by bertnz** [comment]
I am also very keen on knowing the future of this thing.

**Comment by RebeccaMbulaMs** [comment]
Hello @bulebuk and @bertnz (and @algamaes),
My name is Rebecca and I'm the PM for the containers team.
I'm glad to inform you that we are back! We have a new (fantastic) team and are actively working on the project.
We are definitely looking forward to your contributions.
For any questions please email me on: rwambua@microsoft.com.
Kind regards!
