### ISSUE TITLE
Windows nodes are failing to start containerd task when calling LogMonitor.exe

### ISSUE THREAD

**Issue by tmcmm** [microsoft/windows-container-tools#75]
I am running a windows containerd nodepool on the following OS Distro:
**AKSWindows-2019-containerd-17763.3287.220810** which I believe to be the latest
![image](https://user-images.githubusercontent.com/16254825/185900671-8af378e1-6050-4df3-921c-56de535cc84b.png)

And I am getting the following error on the pod events:
Warning  Failed     31m (x5 over 33m)     kubelet            **Error: failed to start containerd task "sm": hcs::System::CreateProcess sm: This version of %1 is not compatible with the version of Windows you're running**. Check your computer's system information and then contact the software publisher.: unknown

The Dockerfile has the following parameter that probably is not ingested by the LogMonitor 
ENTRYPOINT ["C:\\scripts\\logging\\LogMonitor.exe", "C:\\scripts\\startup.ps1"]

So then I tried running logmonitor.exe from inside the pod, it throws the same incompatibility error.

```
PS C:\scripts\logging> .\LogMonitor.exe
Program 'LogMonitor.exe' failed to run: T**he specified executable is not a valid application for this OS platform.At line:1 char:1**
+ .\LogMonitor.exe
+ ~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\LogMonitor.exe
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
Can you please help me on this?

**Comment by iankingori** [comment]
Hi @tmcmm could you share output of `kubectl describe nodes <node-hosting-this>` .

**Comment by iankingori** [comment]
This appears to have been a node specific issue and not a containerd compatibility issue with log monitor. Closing as no repro. Should it recur open the bug again
