### ISSUE TITLE
The Japanese message that Windows Container output turns into garbled characters

### ISSUE THREAD

**Issue by sugiharamika** [microsoft/windows-container-tools#82]
Your LogMonitor outputs the standard output log into AKS node, which was output by Windows container.
English message was properly output into AKS node.
But Japanese message turns into garbled characters such as "???", and output into AKS node.
Does LogMonitor support a Japanese string?

**Comment by iankingori** [comment]
Hi @sugiharamika , is this version 1.1 or version 1.2? We recently released a fix to support UTF-8 encoding which is included in version 1.2.

**Comment by sugiharamika** [comment]
Hi @iankingori ,
Thank you for your reply.
We useing LogMonitor of Verison1.1. I will update to version 1.2 and check if garbled characters do not occur.

**Comment by sugiharamika** [comment]
Hi @iankingori ,
I update to version 1.2 and Japanese string garbled characters do not occur.
Thank you for your help.

**Comment by iankingori** [comment]
Thankyou for the update @sugiharamika.

**Comment by lucillex** [comment]
Hello @sugiharamika! Our team would love to hear feedback on how you are using Log Monitor. We've started a thread [here](https://github.com/microsoft/windows-container-tools/issues/84) and invite you to provide your insights.
